apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels: 
    app: docker-mysql
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: docker-mysql
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      labels: 
        app: docker-mysql
    spec: 
      containers: 
        - name: docker-mysql
          image: mysql 
          env: 
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_ROOT_PASSWORD
              value: test1234
          volumeMounts: 
            - name: configmap-vol
              mountPath: /docker-entrypoint-initdb
            - name: 
      volumes:  
        name: configmap-vol
        configMap: 
          name: mysql-initdb-config
