apiVersion: v1
kind: Service
metadata:
  name: docker-mysql
  labels: 
    app: docker-mysql
spec: 
  selector: 
    app: docker-mysql
    type: NodePort
    ports:
      - port: 5555
        targetPort: 3306
        nodePort: 30222