apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pvc
  labels: 
    app: httpd
spec: 
  accessModes: ReadWriteMany
  capacity: 
    storage: 128M
  hostPath: 
    path: /data/pv
















