apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  labels: 
    app: httpd
spec: 
  accessModes: ReadWriteMany
  resources:
    requests: 64M


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels: 
    app: httpd
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: httpd
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata: 
      labels: 
        app: httpd
    spec: 
      containers: 
        - name: my-container
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /path-of-volume-in-container
              name: my-vol
            - name: mysql-initdb-config
              mountPath: /etc/volume
            - name: my-secret
              mountPath: /etc/secrets
            - name: my-pvc
              mountPath: /data/pvc         
      volumes: 
        - name: my-vol
          hostPath: /path-of-volume-in-node
          type: Directory
        - name: my-config-vol
          configMap: 
            name: mysql-initdb-config
        - name: my-secrets-vol
          secret:
            secretName: my-secret
        - name: my-pvc
          persistentVolumeClaim:
            claimName: my-pvc