appName: CheckoutService
appreplicas: 2
appImage: gcr.io/google-samples/microservices-demo/CheckoutService
appVersion: v0.2.3
containerPort: 5050
containerenvvars: 
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOGUE_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:8080"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7000"

servicePort: 5050