appName: emailservice
appreplicas: 2
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.2.3
containerPort: 8080
containerenvvars: 
- name: PORT
  value: "8080"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

servicePort: 8080