apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongoexpress-dep
  labels:
    app: mongo-express
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: mongo-express
  strategy: 
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports: 
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
              valueFrom: 
                secretKeyRef: 
                  name: momgodb-secret
                  key: mongodb_username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: momgodb-secret
                  key: mongodb_password 
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: momgo-express-configmap
                  key: database_url


--- 
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  selector: 
    app: mongo-express
  type: LoadBalancer
  ports: 
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      protocol: TCP

