apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb-dep
  labels:
    app: mongodb
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: mongodb
  template:
    metadata:
      app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports: 
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: 
                secretKeyRef: 
                  name: momgodb-secret
                  key: mongodb_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  name: momgodb-secret
                  key: mongodb_password  

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  selector: 
    app: mongodb
  type: ClusterIP
  ports: 
    - port: 
      targetPort: 27017
      protocol: TCP