appName: frontend
appreplicas: 2
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.2.3
containerPort: 8080
containerenvvars: 
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOGUE_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:8080"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7000"

servicePort: 8080
servicetype: LoadBalancer
