apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector: 
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports: 
    - port: 8081
      targetPort: 8081
      protocol: TCP